spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: wedding
    password: wedding
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        temp.use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
logging:
  level:
    org.springframework: DEBUG
    org.springframework.transaction.interceptor: TRACE